package com.mycompany.sistemaventa;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;

public class ConsultaInformeLibros extends javax.swing.JFrame {

    /**
     * Creates new form InformeLibros
     */
    public ConsultaInformeLibros() {
        initComponents();
        pintarTabla();
    }

    private void pintarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Nombre del Libro", "Cantidad Vendida", "Fecha", "Precio de Venta"}
        );
        jTable1.setModel(modelo);

        if (SistemaVenta.ventas.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay ventas registradas.");
            return;
        }

        for (Ventas venta : SistemaVenta.ventas) {
            String fecha = venta.fecha.toString();

            for (LibroVendido libro : venta.librosVendidos) {
                double precioTotal = libro.precioIVA * libro.cantidad;
                modelo.addRow(new Object[]{
                    libro.titulo,
                    libro.cantidad,
                    fecha,
                    String.format("%.2f", precioTotal)
                });
            }
        }
    }

    private void exportarInformeCSV() {
        String rutaArchivo = "/home/stephany/NetBeansProjects/SistemaVenta/librosVendidos.txt";
        try (FileWriter writer = new FileWriter(rutaArchivo)) {
            writer.append("Nombre del Libro,Cantidad Vendida,Fecha,Precio de Venta\n");

            for (Ventas venta : SistemaVenta.ventas) {
                String fecha = venta.fecha.toString();

                for (LibroVendido libro : venta.librosVendidos) {
                    double precioTotal = libro.precioIVA * libro.cantidad;
                    writer.append(String.format("%s,%d,%s,%.2f\n",
                            libro.titulo,
                            libro.cantidad,
                            fecha,
                            precioTotal));
                }
            }

            JOptionPane.showMessageDialog(this, "Ventas exportadas a CSV exitosamente.");
        } catch (IOException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al exportar el informe.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        exportarCSV = new javax.swing.JButton();

        jButton1.setBackground(new java.awt.Color(237, 206, 225));
        jButton1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(207, 114, 161));
        jButton1.setText("Cerrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton2.setBackground(new java.awt.Color(237, 206, 225));
        jButton2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(207, 114, 161));
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        exportarCSV.setBackground(new java.awt.Color(237, 206, 225));
        exportarCSV.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        exportarCSV.setForeground(new java.awt.Color(207, 114, 161));
        exportarCSV.setText("exportar csv");
        exportarCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportarCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(exportarCSV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(exportarCSV))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void exportarCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportarCSVActionPerformed
        exportarInformeCSV();
    }//GEN-LAST:event_exportarCSVActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exportarCSV;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
