package com.mycompany.sistemaventa;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Date;

public class NuevaVenta extends javax.swing.JFrame {

    private ArrayList<Libros> libros;
    private ArrayList<LibroVendido> librosVendidos = new ArrayList<>();
    private double totalVenta = 0.0; 

    public NuevaVenta() {
        initComponents();
        llenarComboCupones();
        cargarLibros(); // Cargar libros al inicio
    }

    private void cargarLibros() {
        if (SistemaVenta.libros != null) {
            libros = SistemaVenta.libros;
            for (Libros libro : libros) {
                jComboBox1.addItem(libro.titulo);
            }
        } else {
            System.out.println("No se encontraron libros en el sistema.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")//
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Nit = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IngresarLibro = new javax.swing.JButton();
        Cerrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        NitTexField = new java.awt.TextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        RealizarVenta = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Cantidad1 = new java.awt.TextField();
        Direccion = new javax.swing.JLabel();
        DireccionTextField = new java.awt.TextField();
        NombreCliente = new javax.swing.JLabel();
        ClienteTextField = new java.awt.TextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(207, 114, 161));
        jLabel5.setText("Cantidad:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(207, 114, 161));
        jLabel1.setText("Venta");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 60, 20));

        Nit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Nit.setForeground(new java.awt.Color(207, 114, 161));
        Nit.setText("NIT: ");
        getContentPane().add(Nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(207, 114, 161));
        jLabel3.setText("Precio:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, -1, -1));

        IngresarLibro.setBackground(new java.awt.Color(237, 206, 225));
        IngresarLibro.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        IngresarLibro.setForeground(new java.awt.Color(207, 114, 161));
        IngresarLibro.setText("Ingresar libro");
        IngresarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarLibroActionPerformed(evt);
            }
        });
        getContentPane().add(IngresarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, -1, -1));

        Cerrar.setBackground(new java.awt.Color(237, 206, 225));
        Cerrar.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        Cerrar.setForeground(new java.awt.Color(207, 114, 161));
        Cerrar.setText("Cerrar");
        Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, -1, -1));
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 130, 20));

        NitTexField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NitTexFieldActionPerformed(evt);
            }
        });
        getContentPane().add(NitTexField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 60, 200, 30));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 140, 30));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 130, 20));

        RealizarVenta.setBackground(new java.awt.Color(237, 206, 225));
        RealizarVenta.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        RealizarVenta.setForeground(new java.awt.Color(207, 114, 161));
        RealizarVenta.setText("Realizar la venta");
        RealizarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarVentaActionPerformed(evt);
            }
        });
        getContentPane().add(RealizarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(207, 114, 161));
        jLabel9.setText("Libro:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        Cantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cantidad1ActionPerformed(evt);
            }
        });
        getContentPane().add(Cantidad1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 120, 20));

        Direccion.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        Direccion.setForeground(new java.awt.Color(207, 114, 161));
        Direccion.setText("Dirección:");
        getContentPane().add(Direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        DireccionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DireccionTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DireccionTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 200, 30));

        NombreCliente.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        NombreCliente.setForeground(new java.awt.Color(207, 114, 161));
        NombreCliente.setText("Nombre de cliente:");
        getContentPane().add(NombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        ClienteTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClienteTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ClienteTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 200, 30));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(207, 114, 161));
        jLabel12.setText("Subtotal:");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, -1, -1));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 130, 20));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(207, 114, 161));
        jLabel14.setText("Datos cliente");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 120, 40));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(207, 114, 161));
        jLabel10.setText("cupon:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, -1, -1));

        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 283, 170, 30));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 900, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents
@Override
    public String toString() {
        return "NuevaVenta{" + "libros=" + libros + '}';
    }

    private void actualizarPrecio() {
        String tituloSeleccionado = (String) jComboBox1.getSelectedItem();
        if (tituloSeleccionado != null) {
            for (Libros libro : libros) {
                if (libro.titulo.equals(tituloSeleccionado)) {
                    jLabel8.setText(String.format("%.2f", libro.precioIVA));
                    break;
                }
            }
        }
    }

    private void actualizarTotal() {

        String tituloSeleccionado = (String) jComboBox1.getSelectedItem();
        String cantidadTexto = Cantidad1.getText();

        if (tituloSeleccionado != null && !cantidadTexto.isEmpty()) {
            try {
                int cantidad = Integer.parseInt(cantidadTexto);
                for (Libros libro : libros) {
                    if (libro.titulo.equals(tituloSeleccionado)) {
                        double subtotal = libro.precioIVA * cantidad;
                        jLabel6.setText(String.format("Subtotal: %.2f", subtotal)); // Mostrar subtotal

                        // Calcular el descuento si hay un cupón
                        String cuponSeleccionado = (String) jComboBox2.getSelectedItem();
                        double descuento = 0;
                        if (cuponSeleccionado != null && !cuponSeleccionado.equals("No aplica")) {
                            for (Cupones cupon : SistemaVenta.cupones) {
                                if (cupon.codigo.equals(cuponSeleccionado)) {
                                    if ("Porcentaje".equals(cupon.tipoDescuento)) {
                                        descuento = subtotal * (cupon.valor / 100);
                                    } else if ("Monto fijo".equals(cupon.tipoDescuento)) {
                                        descuento = cupon.valor;
                                    }
                                    break; 
                                }
                            }
                        }
                        // Mostrar el descuento en la interfaz
                        jLabel8.setText(String.format("Descuento: %.2f", descuento)); // Mostrar descuento
                        break;
                    }
                }
            } catch (NumberFormatException e) {
                jLabel6.setText("Cantidad inválida");
            }
        } else {
            jLabel6.setText("");
            jLabel8.setText(""); // Limpiar el descuento si no hay selección
        }
    }

// Método para llenar el JComboBox con cupones
    private void llenarComboCupones() {
        jComboBox2.addItem("No aplica"); // Opción predeterminada
        for (Cupones cupon : SistemaVenta.cupones) {
            jComboBox2.addItem(cupon.codigo); // Agregar los cupones disponibles
        }
    }


    private void IngresarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarLibroActionPerformed
        String tituloSeleccionado = (String) jComboBox1.getSelectedItem();
        if (tituloSeleccionado == null || tituloSeleccionado.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un libro.");
            return;
        }

        int cantidad;
        try {
            cantidad = Integer.parseInt(Cantidad1.getText());
            if (cantidad <= 0) {
                throw new NumberFormatException();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Cantidad inválida.");
            return;
        }

        for (Libros libro : SistemaVenta.libros) {
            if (libro.titulo.equals(tituloSeleccionado)) {
                if (libro.stock < cantidad) {
                    JOptionPane.showMessageDialog(this, "No hay suficiente stock.");
                    return;
                }

                // Verificar si ya se agregó el libro antes
                boolean encontrado = false;
                for (LibroVendido lv : librosVendidos) {
                    if (lv.titulo.equals(libro.titulo)) {
                        lv.cantidad += cantidad;
                        encontrado = true;
                        break;
                    }
                }

               
                if (!encontrado) {
                    librosVendidos.add(new LibroVendido(libro.titulo, libro.precioIVA, cantidad));
                }

                libro.reducirStock(cantidad);
                totalVenta += libro.precioIVA * cantidad;
                jLabel6.setText(String.format("Subtotal: %.2f", totalVenta));
                JOptionPane.showMessageDialog(this, "Libro agregado a la venta.");
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Libro no encontrado.");

    }//GEN-LAST:event_IngresarLibroActionPerformed

    private void CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarActionPerformed
        this.dispose();

    }//GEN-LAST:event_CerrarActionPerformed

    private void NitTexFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NitTexFieldActionPerformed
        actualizarTotal();  // TODO add your handling code here:
    }//GEN-LAST:event_NitTexFieldActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        actualizarPrecio();  // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void RealizarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarVentaActionPerformed
        if (librosVendidos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay libros agregados a la venta.");
            return;
        }

        String nombreCliente = ClienteTextField.getText().trim();
        String nit = NitTexField.getText().trim();
        String direccion = DireccionTextField.getText().trim();

        if (nombreCliente.isEmpty() || nit.isEmpty() || direccion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, completa todos los campos del cliente.");
            return;
        }

        String vendedor = Login.usuarioActual.usuario;
        double totalSinIVA = totalVenta / 1.12;
        double descuento = calcularDescuento(); // Método para calcular el descuento

        // Registrar la venta
        Ventas nuevaVenta = new Ventas(
                totalVenta - descuento, 
                totalSinIVA,
                descuento,
                vendedor,
                nombreCliente,
                nit,
                direccion,
                new Date(),
                new ArrayList<>(librosVendidos)
        );
        SistemaVenta.ventas.add(nuevaVenta);

        JOptionPane.showMessageDialog(this, "Venta realizada correctamente. Total: " + (totalVenta - descuento));

        // Reiniciar campos
        reiniciarCampos();


    }//GEN-LAST:event_RealizarVentaActionPerformed
    private double calcularDescuento() {
        String cuponSeleccionado = (String) jComboBox2.getSelectedItem();
        if (cuponSeleccionado != null && !cuponSeleccionado.equals("No aplica")) {
            for (Cupones cupon : SistemaVenta.cupones) {
                if (cupon.codigo.equals(cuponSeleccionado)) {
                    if ("Porcentaje".equals(cupon.tipoDescuento)) {
                        return totalVenta * (cupon.valor / 100);
                    } else if ("Monto fijo".equals(cupon.tipoDescuento)) {
                        return cupon.valor;
                    }
                }
            }
        }
        return 0;
    }

    private void reiniciarCampos() {
        totalVenta = 0;
        librosVendidos.clear();
        ClienteTextField.setText("");
        NitTexField.setText("");
        DireccionTextField.setText("");
        Cantidad1.setText("");
        jComboBox2.setSelectedIndex(0);
        jComboBox1.setSelectedIndex(-1);
        jLabel6.setText("Subtotal: 0.0");
    }
    private void Cantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cantidad1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cantidad1ActionPerformed

    private void DireccionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DireccionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DireccionTextFieldActionPerformed

    private void ClienteTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClienteTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClienteTextFieldActionPerformed

//
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextField Cantidad1;
    private javax.swing.JButton Cerrar;
    private java.awt.TextField ClienteTextField;
    private javax.swing.JLabel Direccion;
    private java.awt.TextField DireccionTextField;
    private javax.swing.JButton IngresarLibro;
    private javax.swing.JLabel Nit;
    private java.awt.TextField NitTexField;
    private javax.swing.JLabel NombreCliente;
    private javax.swing.JButton RealizarVenta;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
//
}
